config a10s_ghrd_altera_mm_interconnect_181_gwzlhmy_cfg;
		design a10s_ghrd_altera_mm_interconnect_181_gwzlhmy;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.hps_m_master_translator use a10s_ghrd_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.hps_m_master_agent use a10s_ghrd_altera_merlin_master_agent_181.altera_merlin_master_agent;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.arria10_hps_f2h_axi_slave_agent use a10s_ghrd_altera_merlin_axi_slave_ni_181.altera_merlin_axi_slave_ni;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.router use a10s_ghrd_altera_merlin_router_181.a10s_ghrd_altera_merlin_router_181_raxibmi;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.router_001 use a10s_ghrd_altera_merlin_router_181.a10s_ghrd_altera_merlin_router_181_p6yk37i;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.router_002 use a10s_ghrd_altera_merlin_router_181.a10s_ghrd_altera_merlin_router_181_p6yk37i;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.hps_m_master_limiter use a10s_ghrd_altera_merlin_traffic_limiter_181.altera_merlin_traffic_limiter;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.cmd_demux use a10s_ghrd_altera_merlin_demultiplexer_181.a10s_ghrd_altera_merlin_demultiplexer_181_edscloq;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.cmd_mux use a10s_ghrd_altera_merlin_multiplexer_181.a10s_ghrd_altera_merlin_multiplexer_181_3zss3fq;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.cmd_mux_001 use a10s_ghrd_altera_merlin_multiplexer_181.a10s_ghrd_altera_merlin_multiplexer_181_3zss3fq;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.rsp_demux use a10s_ghrd_altera_merlin_demultiplexer_181.a10s_ghrd_altera_merlin_demultiplexer_181_477p4fa;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.rsp_demux_001 use a10s_ghrd_altera_merlin_demultiplexer_181.a10s_ghrd_altera_merlin_demultiplexer_181_477p4fa;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.rsp_mux use a10s_ghrd_altera_merlin_multiplexer_181.a10s_ghrd_altera_merlin_multiplexer_181_qn4gn4i;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.arria10_hps_f2h_axi_slave_wr_cmd_width_adapter use a10s_ghrd_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.arria10_hps_f2h_axi_slave_rd_cmd_width_adapter use a10s_ghrd_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.arria10_hps_f2h_axi_slave_wr_rsp_width_adapter use a10s_ghrd_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
		instance a10s_ghrd_altera_mm_interconnect_181_gwzlhmy.arria10_hps_f2h_axi_slave_rd_rsp_width_adapter use a10s_ghrd_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
endconfig

