config alt_sld_fab_alt_sld_fab_181_awbuhhi_cfg;
		design alt_sld_fab_alt_sld_fab_181_awbuhhi;
		instance alt_sld_fab_alt_sld_fab_181_awbuhhi.presplit use alt_sld_fab_altera_super_splitter_181.alt_sld_fab_altera_super_splitter_181_wgyu6iy;
		instance alt_sld_fab_alt_sld_fab_181_awbuhhi.splitter use alt_sld_fab_altera_sld_splitter_181.alt_sld_fab_altera_sld_splitter_181_wgzq4ca;
		instance alt_sld_fab_alt_sld_fab_181_awbuhhi.sldfabric use alt_sld_fab_altera_sld_jtag_hub_181.alt_sld_fab_altera_sld_jtag_hub_181_x5qrxby;
		instance alt_sld_fab_alt_sld_fab_181_awbuhhi.ident use alt_sld_fab_altera_connection_identification_hub_181.alt_sld_fab_altera_connection_identification_hub_181_iidlfvq;
endconfig

