config alt_sld_fab_alt_sld_fab_181_dbt7qna_cfg;
		design alt_sld_fab_alt_sld_fab_181_dbt7qna;
		instance alt_sld_fab_alt_sld_fab_181_dbt7qna.presplit use alt_sld_fab_altera_super_splitter_181.alt_sld_fab_altera_super_splitter_181_hav7emy;
		instance alt_sld_fab_alt_sld_fab_181_dbt7qna.splitter use alt_sld_fab_altera_sld_splitter_181.alt_sld_fab_altera_sld_splitter_181_zactcby;
		instance alt_sld_fab_alt_sld_fab_181_dbt7qna.sldfabric use alt_sld_fab_altera_sld_jtag_hub_181.alt_sld_fab_altera_sld_jtag_hub_181_usvbikq;
		instance alt_sld_fab_alt_sld_fab_181_dbt7qna.ident use alt_sld_fab_altera_connection_identification_hub_181.alt_sld_fab_altera_connection_identification_hub_181_vo5cady;
endconfig

