config alt_sld_fab_alt_sld_fab_181_2dvnu4a_cfg;
		design alt_sld_fab_alt_sld_fab_181_2dvnu4a;
		instance alt_sld_fab_alt_sld_fab_181_2dvnu4a.presplit use alt_sld_fab_altera_super_splitter_181.alt_sld_fab_altera_super_splitter_181_hav7emy;
		instance alt_sld_fab_alt_sld_fab_181_2dvnu4a.splitter use alt_sld_fab_altera_sld_splitter_181.alt_sld_fab_altera_sld_splitter_181_zactcby;
		instance alt_sld_fab_alt_sld_fab_181_2dvnu4a.sldfabric use alt_sld_fab_altera_sld_jtag_hub_181.alt_sld_fab_altera_sld_jtag_hub_181_usvbikq;
		instance alt_sld_fab_alt_sld_fab_181_2dvnu4a.ident use alt_sld_fab_altera_connection_identification_hub_181.alt_sld_fab_altera_connection_identification_hub_181_57dkocq;
endconfig

