config alt_sld_fab_alt_sld_fab_181_3swojcq_cfg;
		design alt_sld_fab_alt_sld_fab_181_3swojcq;
		instance alt_sld_fab_alt_sld_fab_181_3swojcq.presplit use alt_sld_fab_altera_super_splitter_181.alt_sld_fab_altera_super_splitter_181_wgyu6iy;
		instance alt_sld_fab_alt_sld_fab_181_3swojcq.splitter use alt_sld_fab_altera_sld_splitter_181.alt_sld_fab_altera_sld_splitter_181_wgzq4ca;
		instance alt_sld_fab_alt_sld_fab_181_3swojcq.sldfabric use alt_sld_fab_altera_sld_jtag_hub_181.alt_sld_fab_altera_sld_jtag_hub_181_x5qrxby;
		instance alt_sld_fab_alt_sld_fab_181_3swojcq.ident use alt_sld_fab_altera_connection_identification_hub_181.alt_sld_fab_altera_connection_identification_hub_181_rwbd3ua;
endconfig

