config a10s_ghrd_altera_jtag_avalon_master_181_winiqja_cfg;
		design a10s_ghrd_altera_jtag_avalon_master_181_winiqja;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.jtag_phy_embedded_in_jtag_master use a10s_ghrd_altera_jtag_dc_streaming_181.altera_avalon_st_jtag_interface;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.timing_adt use a10s_ghrd_timing_adapter_181.a10s_ghrd_timing_adapter_181_v2af63i;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.fifo use a10s_ghrd_altera_avalon_sc_fifo_181.altera_avalon_sc_fifo;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.b2p use a10s_ghrd_altera_avalon_st_bytes_to_packets_181.altera_avalon_st_bytes_to_packets;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.p2b use a10s_ghrd_altera_avalon_st_packets_to_bytes_181.altera_avalon_st_packets_to_bytes;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.transacto use a10s_ghrd_altera_avalon_packets_to_master_181.altera_avalon_packets_to_master;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.b2p_adapter use a10s_ghrd_channel_adapter_181.a10s_ghrd_channel_adapter_181_arrjpdi;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.p2b_adapter use a10s_ghrd_channel_adapter_181.a10s_ghrd_channel_adapter_181_xiycpqq;
		instance a10s_ghrd_altera_jtag_avalon_master_181_winiqja.rst_controller use a10s_ghrd_altera_reset_controller_181.altera_reset_controller;
endconfig

