// a10s_ghrd_altera_arria10_hps_io_181_vma6nca.v

// This file was auto-generated from altera_hps_arria10_io_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module a10s_ghrd_altera_arria10_hps_io_181_vma6nca (
		output wire  hps_io_phery_emac0_TX_CLK, // hps_io.hps_io_phery_emac0_TX_CLK
		output wire  hps_io_phery_emac0_TXD0,   //       .hps_io_phery_emac0_TXD0
		output wire  hps_io_phery_emac0_TXD1,   //       .hps_io_phery_emac0_TXD1
		output wire  hps_io_phery_emac0_TXD2,   //       .hps_io_phery_emac0_TXD2
		output wire  hps_io_phery_emac0_TXD3,   //       .hps_io_phery_emac0_TXD3
		input  wire  hps_io_phery_emac0_RX_CTL, //       .hps_io_phery_emac0_RX_CTL
		output wire  hps_io_phery_emac0_TX_CTL, //       .hps_io_phery_emac0_TX_CTL
		input  wire  hps_io_phery_emac0_RX_CLK, //       .hps_io_phery_emac0_RX_CLK
		input  wire  hps_io_phery_emac0_RXD0,   //       .hps_io_phery_emac0_RXD0
		input  wire  hps_io_phery_emac0_RXD1,   //       .hps_io_phery_emac0_RXD1
		input  wire  hps_io_phery_emac0_RXD2,   //       .hps_io_phery_emac0_RXD2
		input  wire  hps_io_phery_emac0_RXD3,   //       .hps_io_phery_emac0_RXD3
		inout  wire  hps_io_phery_emac0_MDIO,   //       .hps_io_phery_emac0_MDIO
		output wire  hps_io_phery_emac0_MDC,    //       .hps_io_phery_emac0_MDC
		inout  wire  hps_io_phery_sdmmc_CMD,    //       .hps_io_phery_sdmmc_CMD
		inout  wire  hps_io_phery_sdmmc_D0,     //       .hps_io_phery_sdmmc_D0
		inout  wire  hps_io_phery_sdmmc_D1,     //       .hps_io_phery_sdmmc_D1
		inout  wire  hps_io_phery_sdmmc_D2,     //       .hps_io_phery_sdmmc_D2
		inout  wire  hps_io_phery_sdmmc_D3,     //       .hps_io_phery_sdmmc_D3
		output wire  hps_io_phery_sdmmc_CCLK,   //       .hps_io_phery_sdmmc_CCLK
		inout  wire  hps_io_phery_usb0_DATA0,   //       .hps_io_phery_usb0_DATA0
		inout  wire  hps_io_phery_usb0_DATA1,   //       .hps_io_phery_usb0_DATA1
		inout  wire  hps_io_phery_usb0_DATA2,   //       .hps_io_phery_usb0_DATA2
		inout  wire  hps_io_phery_usb0_DATA3,   //       .hps_io_phery_usb0_DATA3
		inout  wire  hps_io_phery_usb0_DATA4,   //       .hps_io_phery_usb0_DATA4
		inout  wire  hps_io_phery_usb0_DATA5,   //       .hps_io_phery_usb0_DATA5
		inout  wire  hps_io_phery_usb0_DATA6,   //       .hps_io_phery_usb0_DATA6
		inout  wire  hps_io_phery_usb0_DATA7,   //       .hps_io_phery_usb0_DATA7
		input  wire  hps_io_phery_usb0_CLK,     //       .hps_io_phery_usb0_CLK
		output wire  hps_io_phery_usb0_STP,     //       .hps_io_phery_usb0_STP
		input  wire  hps_io_phery_usb0_DIR,     //       .hps_io_phery_usb0_DIR
		input  wire  hps_io_phery_usb0_NXT,     //       .hps_io_phery_usb0_NXT
		input  wire  hps_io_phery_uart1_RX,     //       .hps_io_phery_uart1_RX
		output wire  hps_io_phery_uart1_TX,     //       .hps_io_phery_uart1_TX
		inout  wire  hps_io_phery_i2c0_SDA,     //       .hps_io_phery_i2c0_SDA
		inout  wire  hps_io_phery_i2c0_SCL,     //       .hps_io_phery_i2c0_SCL
		inout  wire  hps_io_gpio_gpio2_io8,     //       .hps_io_gpio_gpio2_io8
		inout  wire  hps_io_gpio_gpio2_io9,     //       .hps_io_gpio_gpio2_io9
		inout  wire  hps_io_gpio_gpio2_io10,    //       .hps_io_gpio_gpio2_io10
		inout  wire  hps_io_gpio_gpio2_io11,    //       .hps_io_gpio_gpio2_io11
		inout  wire  hps_io_gpio_gpio1_io1,     //       .hps_io_gpio_gpio1_io1
		inout  wire  hps_io_gpio_gpio1_io4      //       .hps_io_gpio_gpio1_io4
	);

	a10s_ghrd_altera_arria10_interface_generator_140_lkc7nyi border (
		.hps_io_phery_emac0_TX_CLK (hps_io_phery_emac0_TX_CLK), // hps_io.hps_io_phery_emac0_TX_CLK
		.hps_io_phery_emac0_TXD0   (hps_io_phery_emac0_TXD0),   //       .hps_io_phery_emac0_TXD0
		.hps_io_phery_emac0_TXD1   (hps_io_phery_emac0_TXD1),   //       .hps_io_phery_emac0_TXD1
		.hps_io_phery_emac0_TXD2   (hps_io_phery_emac0_TXD2),   //       .hps_io_phery_emac0_TXD2
		.hps_io_phery_emac0_TXD3   (hps_io_phery_emac0_TXD3),   //       .hps_io_phery_emac0_TXD3
		.hps_io_phery_emac0_RX_CTL (hps_io_phery_emac0_RX_CTL), //       .hps_io_phery_emac0_RX_CTL
		.hps_io_phery_emac0_TX_CTL (hps_io_phery_emac0_TX_CTL), //       .hps_io_phery_emac0_TX_CTL
		.hps_io_phery_emac0_RX_CLK (hps_io_phery_emac0_RX_CLK), //       .hps_io_phery_emac0_RX_CLK
		.hps_io_phery_emac0_RXD0   (hps_io_phery_emac0_RXD0),   //       .hps_io_phery_emac0_RXD0
		.hps_io_phery_emac0_RXD1   (hps_io_phery_emac0_RXD1),   //       .hps_io_phery_emac0_RXD1
		.hps_io_phery_emac0_RXD2   (hps_io_phery_emac0_RXD2),   //       .hps_io_phery_emac0_RXD2
		.hps_io_phery_emac0_RXD3   (hps_io_phery_emac0_RXD3),   //       .hps_io_phery_emac0_RXD3
		.hps_io_phery_emac0_MDIO   (hps_io_phery_emac0_MDIO),   //       .hps_io_phery_emac0_MDIO
		.hps_io_phery_emac0_MDC    (hps_io_phery_emac0_MDC),    //       .hps_io_phery_emac0_MDC
		.hps_io_phery_sdmmc_CMD    (hps_io_phery_sdmmc_CMD),    //       .hps_io_phery_sdmmc_CMD
		.hps_io_phery_sdmmc_D0     (hps_io_phery_sdmmc_D0),     //       .hps_io_phery_sdmmc_D0
		.hps_io_phery_sdmmc_D1     (hps_io_phery_sdmmc_D1),     //       .hps_io_phery_sdmmc_D1
		.hps_io_phery_sdmmc_D2     (hps_io_phery_sdmmc_D2),     //       .hps_io_phery_sdmmc_D2
		.hps_io_phery_sdmmc_D3     (hps_io_phery_sdmmc_D3),     //       .hps_io_phery_sdmmc_D3
		.hps_io_phery_sdmmc_CCLK   (hps_io_phery_sdmmc_CCLK),   //       .hps_io_phery_sdmmc_CCLK
		.hps_io_phery_usb0_DATA0   (hps_io_phery_usb0_DATA0),   //       .hps_io_phery_usb0_DATA0
		.hps_io_phery_usb0_DATA1   (hps_io_phery_usb0_DATA1),   //       .hps_io_phery_usb0_DATA1
		.hps_io_phery_usb0_DATA2   (hps_io_phery_usb0_DATA2),   //       .hps_io_phery_usb0_DATA2
		.hps_io_phery_usb0_DATA3   (hps_io_phery_usb0_DATA3),   //       .hps_io_phery_usb0_DATA3
		.hps_io_phery_usb0_DATA4   (hps_io_phery_usb0_DATA4),   //       .hps_io_phery_usb0_DATA4
		.hps_io_phery_usb0_DATA5   (hps_io_phery_usb0_DATA5),   //       .hps_io_phery_usb0_DATA5
		.hps_io_phery_usb0_DATA6   (hps_io_phery_usb0_DATA6),   //       .hps_io_phery_usb0_DATA6
		.hps_io_phery_usb0_DATA7   (hps_io_phery_usb0_DATA7),   //       .hps_io_phery_usb0_DATA7
		.hps_io_phery_usb0_CLK     (hps_io_phery_usb0_CLK),     //       .hps_io_phery_usb0_CLK
		.hps_io_phery_usb0_STP     (hps_io_phery_usb0_STP),     //       .hps_io_phery_usb0_STP
		.hps_io_phery_usb0_DIR     (hps_io_phery_usb0_DIR),     //       .hps_io_phery_usb0_DIR
		.hps_io_phery_usb0_NXT     (hps_io_phery_usb0_NXT),     //       .hps_io_phery_usb0_NXT
		.hps_io_phery_uart1_RX     (hps_io_phery_uart1_RX),     //       .hps_io_phery_uart1_RX
		.hps_io_phery_uart1_TX     (hps_io_phery_uart1_TX),     //       .hps_io_phery_uart1_TX
		.hps_io_phery_i2c0_SDA     (hps_io_phery_i2c0_SDA),     //       .hps_io_phery_i2c0_SDA
		.hps_io_phery_i2c0_SCL     (hps_io_phery_i2c0_SCL),     //       .hps_io_phery_i2c0_SCL
		.hps_io_gpio_gpio2_io8     (hps_io_gpio_gpio2_io8),     //       .hps_io_gpio_gpio2_io8
		.hps_io_gpio_gpio2_io9     (hps_io_gpio_gpio2_io9),     //       .hps_io_gpio_gpio2_io9
		.hps_io_gpio_gpio2_io10    (hps_io_gpio_gpio2_io10),    //       .hps_io_gpio_gpio2_io10
		.hps_io_gpio_gpio2_io11    (hps_io_gpio_gpio2_io11),    //       .hps_io_gpio_gpio2_io11
		.hps_io_gpio_gpio1_io1     (hps_io_gpio_gpio1_io1),     //       .hps_io_gpio_gpio1_io1
		.hps_io_gpio_gpio1_io4     (hps_io_gpio_gpio1_io4)      //       .hps_io_gpio_gpio1_io4
	);

endmodule
